version: "3.8"
services:
  mysqlserver:
    build:
      context:
        ./mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=smoothstack
      - MYSQL_PASSWORD=smoothstack
      - MYSQL_DATABASE=utopia
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

volumes:
  mysql_data:
  mysql_config: